### ISSUE TITLE
Cant login after fresh isntall

### ISSUE THREAD

**Issue by 24sevenUK** [simonwep/ocular-docker#3]
### Description

After doing `docker compose up -d` I'm able to navigate to the website, but when I try and login nothing happens and the cloud stays red with a line through it.
Any data entered is lost when the page it reloaded.

In the logs I'm getting the following:-
`nginx-1     | 192.168.1.121 - - [27/May/2024:13:01:52 +0000] "POST /api/login HTTP/1.1" 200 29 "http://192.168.1.122:3030/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
nginx-1     | 192.168.1.121 - - [27/May/2024:13:01:52 +0000] "GET /api/user HTTP/1.1" 403 0 "http://192.168.1.122:3030/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
nginx-1     | 192.168.1.121 - - [27/May/2024:13:01:52 +0000] "GET /api/data/data HTTP/1.1" 401 0 "http://192.168.1.122:3030/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
nginx-1     | 192.168.1.121 - - [27/May/2024:13:01:52 +0000] "GET /api/data/settings HTTP/1.1" 401 0 "http://192.168.1.122:3030/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
nginx-1     | 192.168.1.121 - - [27/May/2024:13:01:52 +0000] "POST /api/logout HTTP/1.1" 401 0 "http://192.168.1.122:3030/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"`

### Environment

Have tried running on:-
- Ubuntu VM with all my other docker containers
- Fresh Debian container

### Expected behaviour

Login to work as expected?

### Steps to reproduce

Followed the instructions on [https://github.com/simonwep/ocular-docker/blob/main/README.md](https://github.com/simonwep/ocular-docker/blob/main/README.md)

**Comment by simonwep** [comment]
Hey! :)

> Any data entered is lost when the page it reloaded.

That is expected if you're not logged in.

> Ubuntu VM with all my other docker containers
> Fresh Debian container

Have you tried running it without any other docker containers running? And what do you mean with "Fresh debian container"?

> Followed the instructions on https://github.com/simonwep/ocular-docker/blob/main/README.md

When I do this it works.
![demo](https://github.com/simonwep/ocular-docker/assets/30767528/d96b4228-2baf-4e94-930c-38c36bd4fc09)

Please provide all steps/information necessary to reproduce that. You skipped a whole lot of information there, the GIF is from a Apple M2 Pro with Docker 26.1.1. Maybe related to #2?

**Comment by jd-apprentice** [comment]
I'm running the same issue, i've tried to docker compose up -d, app is running fine but can't login. Also tried to run the ./gen-password then docker compose up -d --force-recreate and no case

**Comment by simonwep** [comment]
@jd-apprentice 

> wget https://github.com/simonwep/ocular-docker/archive/refs/tags/v1.2.0.zip
unzip v1.2.0.zip
cd ocular-docker
cp .env.example .env
./gen-passwords.sh
docker compose up -d

Aren't these literally the setup instructions from this repo? https://github.com/simonwep/ocular-docker?tab=readme-ov-file#first-time-setup 

> In the previous attempt I made I cloned the repository and also ran docker compose up -d before running ./gen-passwords

Well, I wouldn't expect it to work if you don't follow the instructions 😅

**Comment by Talha771** [comment]
IM having the same problem as the dude above, I've pruned and followed the instructions multiple times but it returns invalid creds

**Comment by simonwep** [comment]
Please open a new issue if you're having troubles getting this set up, this thread is getting to bloated :)
