### ISSUE TITLE
Checking for compose v1

### ISSUE THREAD

**Issue by tyler46** [simonwep/ocular-docker#7]
### Support guidelines

- [X] I've read the [FAQs](https://github.com/simonwep/ocular-docker?tab=readme-ov-file#faq)

### Description

It looks like that when running `setup.sh` as suggested in Quick start section, script is checking whether `docker-compose` command exists or not. Since compose v1 has been deprecated and script actually uses `docker compose up -d`, I think command check should become like:
```bash
if ! command_exists "docker compose"; then
  echo "Docker Compose is not available. Please install the latest version of Docker and try again."
  exit 1
fi
```

and `command_exists` to altered like:

```bash
command_exists() {
  $1 &>/dev/null
}
```

### Environment

- OS: Pop!_OS 22.04 LTS
- version: 1.5.0
- Docker version 27.3.1, build ce12230
- Docker Compose version v2.29.7

### Expected behaviour

Setup script should run without complaining about missing docker compose.

### Steps to reproduce

Run `bash <(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/simonwep/ocular-docker/refs/heads/main/setup.sh)`

**Comment by simonwep** [comment]
Good point, I totally missed that `docker-compose` is deprecated when writing the script 🤦 Thank's for the issue!
